### ISSUE TITLE
[BUG] application not working

### ISSUE THREAD

**Issue by Brijesh1963** [devs-in-tech/DevsInTech#441]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Application not working in any devices.....
![not_working](https://github.com/devs-in-tech/DevsInTech/assets/98037970/2ad83634-01ff-45da-9d96-d6a1bd451396)

**Comment by suveshmoza** [comment]
I am also facing the same issue. Attaching the log files
[devsintech.vercel.app-1692374524636.log](https://github.com/devs-in-tech/DevsInTech/files/12381157/devsintech.vercel.app-1692374524636.log)

**Comment by theunhackable** [comment]
@Susmita-Dey I have gone through the code. Everything looks good. I think the `AlanAIProjectKey` might have changed. For now removing the component seems like an option or just update the APIkey. I tried it and it worked well.

**Comment by Susmita-Dey** [comment]
Hey @theunhackable Kindly create a PR and remove that component

**Comment by theunhackable** [comment]
@Susmita-Dey I have made required changes. I got into trouble through ESLint errors due to ambigious TailwindCSS classes, usage of `class` instead of `className` and img tags I also fixed them which are restricting me to make a commit. I would like you to review the code and give feedback if any necessary changes are to be made. Thanks ❤️
